project:
  type: book

book:
  title: "Shell Notes"
  author: "Kittipos Sirivongrungson"
  date: today
  repo-url: https://github.com/Lightbridge-KS/shell-notes
  site-url: https://shell-notes-lightbridge.netlify.app
  chapters:
    - index.qmd
    - part: Bash Scripting
      chapters: 
        - text: "Overview"
          href: "contents/bash-scripting/00-crashcourse-overview.qmd"
        - text: "Foundation"
          href: "contents/bash-scripting/01-foundation.qmd"
        - text: "Variable & Data"
          href: "contents/bash-scripting/02-variable-data.qmd"
        - text: "Input & Output"
          href: "contents/bash-scripting/03-input-output.qmd"
        - text: "Control Flow"
          href: "contents/bash-scripting/04-control-flow.qmd"
        - text: "Functions"
          href: "contents/bash-scripting/05-functions.qmd"
        - text: "Text Processing"
          href: "contents/bash-scripting/06-text-processing.qmd"
        - text: "File & Directory"
          href: "contents/bash-scripting/07-file-directory.qmd"
        - text: "Practical Patterns"
          href: "contents/bash-scripting/08-practical-patterns.qmd"
    - part: Tricks Explained
      chapters: 
        - text: Here Doc
          href: "contents/tricks/here_documents.qmd"
        - target: Stick Mode
          href: "contents/tricks/bash-strick-mode.qmd"
        - target: Parent vs Child Shell
          href: "contents/tricks/parent-vs-child-shell.qmd"
    - part: Linux 
      chapters: 
        - text: File Permission
          href: "contents/permission/linux-file-permission.qmd"


format:
  html:
    theme:
      light:
      - cosmo
      - brand
      dark: 
      - darkly
    toc-depth: 4


freeze: auto




